version: '3.8'
services:
  haooho-db:
    image: mysql/mysql-server:8.0 #mysql版本
    command: 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - D:/depo/mysql8/data:/var/lib/mysql:rw
      - D:/depo/mysql8/conf:/etc/mysql/conf.d:rw
      - D:/depo/mysql8/init:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 33416:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=haoohoCyber #访问密码
      - MYSQL_DATABASE=depo
      - MYSQL_USER=cyberkeon
      - MYSQL_PASSWORD=haoohoCyber
  
  haooho-depo:
    image: docker.io/haosky/haodepo:1.0 
    restart: always
    ports:
      - 8367:8367
    environment:
      - TZ=Asia/Shanghai